FROM ubuntu:17.10
# Update
RUN apt-get update
RUN apt-get install -y python2.7
RUN apt-get install -y python-pip

# Install app dependencies
RUN pip install pip==9.0.1
RUN pip install virtualenv==15.1.0
RUN pip install pyinstaller==3.2.1
